# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d06acfd119169af0b3b49fde69004b65a7077491562f19da1d125aeb9ad380da50bfc374cb465ce11cfd7cb83155c6dca5b83709f1b2e43169510ff99ed4a1

test:
  secret_key_base: db9cf1db610f8d978d1fd60170dede1fc5812c1f862270a123c9bae2226e681652154890dadab1dd1a3bca5a4ef5c3333b119712cef14439b7b03c698b3f9d96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
